// Vaultline Storefront — app-live.js
// Live Fourthwall catalog, collection routing, cart, checkout, and quick view.

const STORE_URL='https://vaultlineofficial-shop.fourthwall.com';
const CART_KEY='vaultline_fourthwall_cart_id';
const COLLECTIONS={'deadstep-2':{name:'DEADSTEP'},'submerged':{name:'CURRENT BETWEEN'},'mens':{name:'OMEGA'},'womens':{name:'ALPHA'},'grave-offerings':{name:'GRAVE OFFERINGS'},'fractured-liberty':{name:'FRACTURED LIBERTY'}};
const COLLECTION_COVER_OFFERS={
  'deadstep-2':'a6d1a51d-dbc2-443e-ae40-b63aa063d162',
  'submerged':'9b247c1b-98a5-4e22-ac7a-67d5a32ac0b2',
  'mens':'123cfbfc-9f7b-4b46-8922-d24b74577abe',
  'womens':'26be87d7-fa56-48fa-a361-712e23bf675f',
  'grave-offerings':'b5f2171f-4bf6-4414-b00e-3f03d0d01495',
  'fractured-liberty':'61ee0527-9900-4185-b526-fa285a7220cf'
};
const fallbackProducts=[];let allProducts=[];let products=[];let catalogLive=false;let activeCollection=null;const collectionCache=new Map();
const $=s=>document.querySelector(s);const grid=$('#product-grid'),status=$('#catalog-status'),drawer=$('#cart-drawer'),scrim=$('#scrim'),cartButton=$('#cart-button'),cartClose=$('#cart-close'),checkout=$('#checkout-button'),cartItems=$('#cart-items'),cartCount=$('#cart-count'),cartTotal=$('#cart-total'),quick=$('#quick-view'),quickClose=$('#quick-close'),quickImage=$('#quick-image'),quickName=$('#quick-name'),quickDesc=$('#quick-description'),quickIndex=$('#quick-index'),quickSwatches=$('#quick-swatches'),quickVariants=$('#quick-variants'),quickPrice=$('#quick-price'),quickBuy=$('#quick-buy'),quickColorLabel=$('#quick-color-label'),quickThumbs=$('#quick-thumbs'),shopTitle=$('#shop-title'),shopKicker=$('#shop-kicker'),menuToggle=$('#menu-toggle'),mobNav=$('#mob-nav');
const money=(v,c='USD')=>new Intl.NumberFormat('en-US',{style:'currency',currency:c}).format(Number(v)||0);const esc=(v='')=>String(v).replace(/[&<>'\"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[ch]||ch));const clean=(v='')=>String(v).replace(/<[^>]*>/g,'').trim();const ok=v=>!(v?.stock?.type==='LIMITED'&&Number(v?.stock?.inStock||0)<=0);const imgUrl=i=>i?.transformedUrl||i?.url||'';const vImg=v=>imgUrl(v?.images?.[0]);const vColor=v=>v?.attributes?.color?.name||'';const vSwatch=v=>v?.attributes?.color?.swatch||'';const vSize=v=>v?.attributes?.size?.name||'';const swatchLabel=(p,c)=>p?.variants?.find(v=>vSwatch(v)===c&&vColor(v))?.attributes?.color?.name||'Color option';
function uniqImages(items){const seen=new Set(),out=[];for(const i of items||[]){const u=typeof i==='string'?i:imgUrl(i);if(u&&!seen.has(u)){seen.add(u);out.push(u)}}return out}function productImages(p,variants){return uniqImages([...(p.images||[]),...variants.flatMap(v=>v.images||[])])}
function normalize(payload){const list=Array.isArray(payload)?payload:(payload.products||payload.data||payload.items||[]);return list.map(p=>{const variants=Array.isArray(p.variants)?p.variants:[];const priced=variants.find(ok)||variants[0];const images=productImages(p,variants);const colors=[...new Set(variants.map(v=>vSwatch(v)).filter(Boolean))];return{id:p.id||p.offerId||'',name:p.name||p.title||'Vaultline piece',slug:p.slug||p.handle||p.id,price:p.price?.amount||p.price||priced?.unitPrice?.value||0,currency:p.price?.currency||p.currency||priced?.unitPrice?.currency||'USD',image:p.primaryImageUrl||images[0]||'',images,copy:clean(p.description)||'',colors:colors.length?colors:['#151515'],variants}})}
function cardHTML(p,i){const swatches=p.colors.slice(0,6).map((c,ci)=>`<button type="button" class="sw${ci===0?' is-sel':''}" style="--sw:${esc(c)}" data-swatch="${esc(c)}" aria-label="Select ${esc(swatchLabel(p,c))}"></button>`).join('');return `<article class="p-card" data-idx="${i}"><div class="p-card-img" data-trigger="quick" data-index="${i}"><img src="${esc(p.image)}" alt="${esc(p.name)}" loading="lazy"></div><div class="p-card-body"><div class="p-card-name">${esc(p.name)}</div><div class="p-card-price">${money(p.price,p.currency)}</div><div class="p-card-swatches">${swatches}</div></div></article>`}
function render(list,live,statusText){products=list;grid.innerHTML=list.length?list.map(cardHTML).join(''):'<div class="collection-empty">No products found in this collection.</div>';status.textContent=statusText||(live?`${list.length} PRODUCTS`:'STAGED')}function showAllProducts(){activeCollection=null;shopKicker.textContent='SHOP';shopTitle.textContent='CURRENT PIECES';render(allProducts,catalogLive)}
async function fetchCollection(slug,force=false){if(!force&&collectionCache.has(slug))return collectionCache.get(slug);const r=await fetch(`/api/storefront/collections/${encodeURIComponent(slug)}/products`,{headers:{Accept:'application/json'}});if(!r.ok)throw new Error(`Collection request failed (${r.status})`);const list=normalize(await r.json());collectionCache.set(slug,list);return list}
async function showCollection(slug){const col=COLLECTIONS[slug];if(!col)return;activeCollection=slug;shopKicker.textContent='COLLECTION';shopTitle.textContent=col.name;status.textContent='LOADING…';grid.innerHTML='<div class="collection-empty">Loading collection…</div>';$('#shop')?.scrollIntoView({behavior:'smooth',block:'start'});try{const list=await fetchCollection(slug,true);if(activeCollection===slug)render(list,true,`${list.length} PRODUCTS`)}catch(e){console.error(e);if(activeCollection===slug)render([],false,'LOAD ERROR')}}
function collectionCover(list,slug){const pinnedId=COLLECTION_COVER_OFFERS[slug];const pinned=list.find(p=>p.id===pinnedId&&p.image);if(pinned)return pinned.image;const preferred=list.find(p=>p.image&&!/(gift card|sticker|mug|tote)/i.test(p.name));return preferred?.image||list.find(p=>p.image)?.image||''}
async function hydrateCollectionCards(){await Promise.allSettled([...document.querySelectorAll('[data-collection]')].map(async card=>{const slug=card.dataset.collection;const list=await fetchCollection(slug);const count=card.querySelector('.col-card-inner p');if(count)count.textContent=`${list.length} PIECES`;const cover=collectionCover(list,slug);if(cover)card.style.setProperty('--collection-cover',`url("${cover.replace(/"/g,'%22')}")`);card.dataset.loaded='true'}))}
async function loadCatalog(){status.textContent='LOADING…';try{const r=await fetch('/api/storefront/products',{headers:{Accept:'application/json'}});if(!r.ok)throw new Error(`Catalog request failed (${r.status})`);allProducts=normalize(await r.json());if(!allProducts.length)throw new Error('Catalog returned no products');catalogLive=true;if(!activeCollection)showAllProducts();await openProductFromLocation()}catch(e){console.error(e);catalogLive=false;render([],false,'LOAD ERROR')}hydrateCollectionCards()}
function galleryFor(p,swatch=null){const variants=swatch?p.variants.filter(v=>vSwatch(v)===swatch):p.variants;return uniqImages([...(p.images||[]),...variants.flatMap(v=>v.images||[])])}function renderThumbs(p,swatch=null,preferred=null){const imgs=galleryFor(p,swatch);if(preferred&&!imgs.includes(preferred))imgs.unshift(preferred);const active=preferred||imgs[0]||p.image;quickThumbs.innerHTML=imgs.map((img,i)=>`<button class="pd-thumb${img===active||(!preferred&&i===0)?' is-sel':''}" data-thumb-src="${esc(img)}"><img src="${esc(img)}" alt="${esc(p.name)} view ${i+1}" loading="lazy"></button>`).join('');if(active)quickImage.src=active;quickThumbs.querySelectorAll('.pd-thumb').forEach(tb=>tb.onclick=()=>{quickThumbs.querySelectorAll('.pd-thumb').forEach(t=>t.classList.remove('is-sel'));tb.classList.add('is-sel');quickImage.src=tb.dataset.thumbSrc})}window.__vaultlineRenderGallery=(p,swatch,preferred)=>renderThumbs(p,swatch,preferred);
grid.addEventListener('click',e=>{const sw=e.target.closest('.p-card-swatches .sw');if(sw){e.stopPropagation();const card=sw.closest('.p-card'),p=products[+card.dataset.idx];card.querySelectorAll('.sw').forEach(s=>s.classList.remove('is-sel'));sw.classList.add('is-sel');const match=p?.variants.find(v=>vSwatch(v)===sw.dataset.swatch);if(match){const img=vImg(match);if(img)card.querySelector('img').src=img}card.dataset.selectedSwatch=sw.dataset.swatch;return}const trigger=e.target.closest('[data-trigger="quick"]');if(trigger)openQuick(+trigger.dataset.index)});
function productPath(p){return '/products/'+encodeURIComponent(String(p?.slug||p?.id||'').trim())}
function syncProductMeta(p){const url=new URL(productPath(p),location.origin).toString();document.title=`${p.name} | Vaultline by Gizzy Graves`;const set=(sel,attr,val)=>{const el=document.querySelector(sel);if(el)el.setAttribute(attr,val)};set('link[rel="canonical"]','href',url);set('meta[property="og:type"]','content','product');set('meta[property="og:title"]','content',p.name);set('meta[property="og:description"]','content',p.copy||'Vaultline by Gizzy Graves');set('meta[property="og:image"]','content',p.image||'');set('meta[property="og:url"]','content',url);set('meta[name="twitter:title"]','content',p.name);set('meta[name="twitter:description"]','content',p.copy||'Vaultline by Gizzy Graves');set('meta[name="twitter:image"]','content',p.image||'')}
function resetProductMeta(){document.title='Vaultline by Gizzy Graves';const home=location.origin+'/';const set=(sel,attr,val)=>{const el=document.querySelector(sel);if(el)el.setAttribute(attr,val)};set('link[rel="canonical"]','href',home);set('meta[property="og:type"]','content','website');set('meta[property="og:title"]','content','Vaultline by Gizzy Graves');set('meta[property="og:url"]','content',home)}
function openProduct(p,{push=true}={}){const i=products.findIndex(x=>x.id===p.id);if(i<0){products=[...products,p]}openQuick(products.findIndex(x=>x.id===p.id),{push})}
function openQuick(i,{push=true}={}){const p=products[i];if(!p)return;window.__quickProduct=p;if(push&&location.pathname!==productPath(p))history.pushState({product:p.slug||p.id},'',productPath(p));syncProductMeta(p);const card=grid.querySelector(`.p-card[data-idx="${i}"]`);window.__quickColorSwatch=card?.dataset.selectedSwatch||null;quickName.textContent=p.name;quickDesc.textContent=p.copy;quickIndex.textContent=activeCollection?COLLECTIONS[activeCollection]?.name||'VAULTLINE':'VAULTLINE';quickPrice.textContent=money(p.price,p.currency);if(quickColorLabel)quickColorLabel.textContent='';renderThumbs(p,window.__quickColorSwatch);quickSwatches.innerHTML=p.colors.map((c,ci)=>`<button type="button" class="sw" style="--sw:${esc(c)}" data-swatch="${esc(c)}" aria-label="Color ${ci+1}"></button>`).join('');quickVariants.innerHTML=p.variants.map(v=>{const display=vSize(v)||vColor(v)||'Default';return `<button type="button" class="sz" data-vid="${esc(v.id)}" data-swatch="${esc(vSwatch(v))}" data-size="${esc(vSize(v))}" ${ok(v)?'':'disabled'}>${esc(display)}</button>`}).join('');quickBuy.textContent=p.variants.length?'ADD TO CART':'UNAVAILABLE';quickBuy.dataset.mode=p.variants.length?'cart':'unavailable';const d=$('#pd-details-text');if(d)d.textContent=p.copy||'Materials, construction, and available options vary by piece. Review the selected product and variant before checkout.';quick.classList.add('open');scrim.classList.add('open');quick.setAttribute('aria-hidden','false');document.body.classList.add('locked')}
function closeQuick({fromPop=false}={}){if(!fromPop&&location.pathname.startsWith('/products/'))history.pushState({},'', '/');resetProductMeta();quick.classList.remove('open');quick.setAttribute('aria-hidden','true');if(!drawer.classList.contains('open'))scrim.classList.remove('open');document.body.classList.remove('locked')}async function api(path,opt={}){const r=await fetch(path,{...opt,headers:{Accept:'application/json','Content-Type':'application/json',...(opt.headers||{})}});const body=await r.json().catch(()=>({}));if(!r.ok)throw new Error(body.error||body.message||`Failed (${r.status})`);return body}async function ensureCart(){const id=localStorage.getItem(CART_KEY);if(id){try{return await api(`/api/cart/${encodeURIComponent(id)}`)}catch{localStorage.removeItem(CART_KEY)}}const cart=await api('/api/cart',{method:'POST',body:'{"items":[]}'});localStorage.setItem(CART_KEY,cart.id);return cart}function cartMath(cart){let count=0,total=0,currency='USD';for(const item of cart?.items||[]){const q=Number(item.quantity)||0,p=Number(item?.variant?.unitPrice?.value)||0;count+=q;total+=q*p;currency=item?.variant?.unitPrice?.currency||currency}return{count,total,currency}}function cartRequestItem(item,quantity){const out={variantId:item?.variant?.id,quantity};if(item?.groupedBy?.bundleId)out.bundleId=item.groupedBy.bundleId;return out}function showCart(cart){const m=cartMath(cart);cartCount.textContent=m.count;cartTotal.textContent=money(m.total,m.currency);checkout.disabled=!cart?.id||!m.count;cartItems.innerHTML=(cart?.items||[]).length?(cart.items.map((item,i)=>{const q=Math.max(1,Number(item.quantity)||1);const variant=item?.variant||{};const detail=variant?.attributes?.description||[variant?.attributes?.color?.name,variant?.attributes?.size?.name].filter(Boolean).join(' / ');return `<article class="cart-line" data-cart-index="${i}"><div class="cart-line-copy"><strong>${esc(variant?.product?.name||variant?.name||'Vaultline piece')}</strong>${detail?`<span class="cart-line-detail">${esc(detail)}</span>`:''}</div><div class="cart-line-actions"><div class="cart-qty" aria-label="Quantity controls"><button type="button" data-cart-action="minus" aria-label="Decrease quantity">−</button><span>${q}</span><button type="button" data-cart-action="plus" aria-label="Increase quantity">+</button></div><button type="button" class="cart-remove" data-cart-action="remove" aria-label="Remove item">REMOVE</button></div></article>`}).join('')):'<p class="cart-empty">Your cart is empty.</p>';cartItems._cart=cart}async function openCart(){drawer.classList.add('open');scrim.classList.add('open');drawer.setAttribute('aria-hidden','false');document.body.classList.add('locked');try{showCart(await ensureCart())}catch(e){console.error(e)}}function closeCart(){drawer.classList.remove('open');drawer.setAttribute('aria-hidden','true');if(!quick.classList.contains('open'))scrim.classList.remove('open');document.body.classList.remove('locked')}
quickBuy?.addEventListener('click',async()=>{const p=window.__quickProduct;if(!p||quickBuy.dataset.mode!=='cart')return;const selected=quickVariants.querySelector('.sz.is-sel:not([disabled])')||quickVariants.querySelector('.sz:not([disabled])');const variantId=selected?.dataset.vid||p.variants.find(ok)?.id;if(!variantId)return;quickBuy.disabled=true;try{const cart=await ensureCart();const updated=await api(`/api/cart/${encodeURIComponent(cart.id)}/add`,{method:'POST',body:JSON.stringify({items:[{variantId,quantity:1}]})});showCart(updated);closeQuick();await openCart()}catch(e){console.error(e)}finally{quickBuy.disabled=false}});
cartItems?.addEventListener('click',async e=>{const button=e.target.closest('[data-cart-action]');if(!button)return;const line=button.closest('.cart-line');const cart=cartItems._cart;const item=cart?.items?.[Number(line?.dataset.cartIndex)];if(!cart?.id||!item?.variant?.id)return;const action=button.dataset.cartAction;const current=Math.max(1,Number(item.quantity)||1);button.disabled=true;try{let updated;if(action==='plus'){updated=await api(`/api/cart/${encodeURIComponent(cart.id)}/change`,{method:'POST',body:JSON.stringify({items:[cartRequestItem(item,current+1)]})})}else if(action==='minus'){if(current<=1){updated=await api(`/api/cart/${encodeURIComponent(cart.id)}/remove`,{method:'POST',body:JSON.stringify({items:[cartRequestItem(item,current)]})})}else{updated=await api(`/api/cart/${encodeURIComponent(cart.id)}/change`,{method:'POST',body:JSON.stringify({items:[cartRequestItem(item,current-1)]})})}}else if(action==='remove'){updated=await api(`/api/cart/${encodeURIComponent(cart.id)}/remove`,{method:'POST',body:JSON.stringify({items:[cartRequestItem(item,current)]})})}if(updated)showCart(updated)}catch(err){console.error(err)}finally{button.disabled=false}});
checkout?.addEventListener('click',async()=>{try{const cart=await ensureCart();const {currency}=cartMath(cart);if(!cart?.id)throw new Error('Cart ID unavailable');const checkoutUrl=new URL('/checkout/',STORE_URL);checkoutUrl.searchParams.set('cartCurrency',currency||'USD');checkoutUrl.searchParams.set('cartId',cart.id);location.href=checkoutUrl.toString()}catch(e){console.error(e)}});
async function openProductFromLocation(){const m=location.pathname.match(/^\/products\/([^/]+)\/?$/);if(!m)return;const key=decodeURIComponent(m[1]);let p=allProducts.find(x=>String(x.slug)===key||String(x.id)===key);if(!p){for(const slug of Object.keys(COLLECTIONS)){const list=await fetchCollection(slug).catch(()=>[]);p=list.find(x=>String(x.slug)===key||String(x.id)===key);if(p)break}}if(p){if(!products.some(x=>x.id===p.id))products=[...products,p];openProduct(p,{push:false})}}
window.addEventListener('popstate',()=>{if(location.pathname.startsWith('/products/'))openProductFromLocation();else if(quick.classList.contains('open'))closeQuick({fromPop:true})});
cartButton?.addEventListener('click',openCart);cartClose?.addEventListener('click',closeCart);quickClose?.addEventListener('click',closeQuick);scrim?.addEventListener('click',()=>{closeQuick();closeCart()});menuToggle?.addEventListener('click',()=>{mobNav?.classList.toggle('open');menuToggle.setAttribute('aria-expanded',String(mobNav?.classList.contains('open')))});document.querySelectorAll('[data-collection]').forEach(card=>card.addEventListener('click',e=>{e.preventDefault();showCollection(card.dataset.collection)}));document.querySelectorAll('[data-shop-all]').forEach(a=>a.addEventListener('click',()=>setTimeout(showAllProducts,0)));$('#refresh-products')?.addEventListener('click',()=>{collectionCache.clear();loadCatalog()});loadCatalog();