const STORE_URL='https://vaultlineofficial.us';
const CART_KEY='vaultline_fourthwall_cart_id';
const fallbackProducts=[
{name:'In Ruin We Trust Slides',slug:'in-ruin-we-trust-slides',price:36,image:'https://cdn.fourthwall.com/customizations/sh_0e0db572-47ce-453b-a747-142819f87a74/699ce60f-5fb4-4dcb-855a-74d3f865b6ee.png',accent:'steel',copy:'Built for the aftermath. Dark, understated, and unmistakably Vaultline.',colors:['#0e0c0f','#f1f1ef'],variants:[]},
{name:'White Sigil Rib Tank',slug:'white-sigil-rib-tank',price:25,image:'https://cdn.fourthwall.com/customizations/sh_0e0db572-47ce-453b-a747-142819f87a74/26b306d0-ab15-4974-9a9e-8729093d77d6.webp',accent:'pearl',copy:'Minimal from the front. Quietly marked from behind.',colors:['#0c0c0c','#243048','#aeb0b2'],variants:[]},
{name:'Crimson Thorn Baby Tee',slug:'crimson-thorn-baby-tee-vaultline-by-gizzy-graves',price:37,image:'https://cdn.fourthwall.com/customizations/sh_0e0db572-47ce-453b-a747-142819f87a74/54978fa7-1209-4d1c-9283-ff4f848068a1.webp',accent:'crimson',copy:'The front stays restrained. The back carries the damage.',colors:['#19171b','#3c2926','#e6e7e9'],variants:[]},
{name:'Northern Fracture Hoodie',slug:'vaultline-northern-fracture-hoodie',price:62,image:'https://cdn.fourthwall.com/customizations/sh_0e0db572-47ce-453b-a747-142819f87a74/69a3a0b2-52a8-4383-954c-f7c5383ceef2.webp',accent:'vault',copy:'Heavy structure. Northern Star. Controlled fracture.',colors:['#0f0f0f','#30478a','#aeb0b2'],variants:[]},
{name:'Northern Thorn Cami',slug:'northern-thorn-cami-vaultline',price:25,image:'https://cdn.fourthwall.com/customizations/sh_0e0db572-47ce-453b-a747-142819f87a74/6099ed73-bac7-49c4-ac3d-514c6c67aca0.png',accent:'crimson',copy:'A softer silhouette without losing the edge.',colors:['#0c0c0c'],variants:[]},
{name:'IXXI Vaultline Tee',slug:'ixxi-vaultline-tee',price:38,image:'https://cdn.fourthwall.com/offer/sh_0e0db572-47ce-453b-a747-142819f87a74/00db2ce5-1ceb-4aee-8ad5-673047373ab1.png',accent:'pearl',copy:'IXXI at the front. Vaultline fracture language at the back.',colors:['#424242'],variants:[]},
{name:'Half Butterfly Fracture Baby Tee',slug:'half-butterfly-fracture-baby-tee',price:38,image:'https://cdn.fourthwall.com/customizations/sh_0e0db572-47ce-453b-a747-142819f87a74/bbf26803-a430-4b71-af64-5167312caf82.webp',accent:'crimson',copy:'Transformation without erasure. Split through the fracture.',colors:['#19171b'],variants:[]},
{name:'Vaultline Gift Card',slug:'vaultline-gift-card',price:25,image:'https://cdn.fourthwall.com/offer/sh_0e0db572-47ce-453b-a747-142819f87a74/c2f2de89-d029-47a8-8446-ab2cabd39270.png',accent:'steel',copy:'Give them access to the Vault. Let them choose the piece.',colors:['#11151c'],variants:[]}
];
let products=fallbackProducts,quickProduct=null;
const $=s=>document.querySelector(s),grid=$('#product-grid'),status=$('#catalog-status'),nav=$('#site-nav'),toggle=$('.nav-toggle'),drawer=$('#cart-drawer'),scrim=$('#scrim'),cartButton=$('#cart-button'),cartClose=$('#cart-close'),checkout=$('#checkout-button'),cartItems=$('#cart-items'),cartCount=$('#cart-count'),cartTotal=$('#cart-total'),quick=$('#quick-view'),quickClose=$('#quick-close'),quickImage=$('#quick-image'),quickName=$('#quick-name'),quickDescription=$('#quick-description'),quickIndex=$('#quick-index'),quickSwatches=$('#quick-swatches'),quickVariants=$('#quick-variants'),quickPrice=$('#quick-price'),quickBuy=$('#quick-buy');
const money=(v,c='USD')=>new Intl.NumberFormat('en-US',{style:'currency',currency:c}).format(Number(v)||0);
const esc=(v='')=>String(v).replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]));
const clean=(v='')=>String(v).replace(/<[^>]*>/g,'').trim();
const available=v=>!(v?.stock?.type==='LIMITED'&&Number(v?.stock?.inStock||0)<=0);
const label=v=>[v?.attributes?.color?.name,v?.attributes?.size?.name].filter(Boolean).join(' / ')||v?.name||'Default';
function normalize(payload){const list=Array.isArray(payload)?payload:(payload.products||payload.data||payload.items||[]);return list.map((p,i)=>{const variants=Array.isArray(p.variants)?p.variants:[],priced=variants.find(available)||variants[0],colors=[...new Set(variants.map(v=>v?.attributes?.color?.swatch).filter(Boolean))];return{name:p.name||p.title||'Vaultline piece',slug:p.slug||p.handle||p.id,price:p.price?.amount||p.price||priced?.unitPrice?.value||0,currency:p.price?.currency||p.currency||priced?.unitPrice?.currency||'USD',image:p.primaryImageUrl||p.image?.url||p.images?.[0]?.transformedUrl||p.images?.[0]?.url||'',copy:clean(p.description)||'A piece pulled from the current Vaultline catalog.',accent:i%3===0?'crimson':i%3===1?'pearl':'steel',colors:colors.length?colors:['#151515'],variants}})}
function render(list,live){products=list;grid.innerHTML=list.map((p,i)=>`<article class="product-card accent-${p.accent}"><div class="dossier-head"><div class="dossier-title"><span class="dossier-number">${String(i+1).padStart(2,'0')}.</span><h3>${esc(p.name)}</h3></div><p>${esc((p.copy||'').slice(0,180))}</p></div><button class="product-visual quick-trigger" data-index="${i}"><img src="${esc(p.image)}" alt="${esc(p.name)}" loading="lazy"><span class="view-stamp">INSPECT PIECE</span></button><div class="colorway-label">COLORWAYS</div><div class="colorway-row"><div class="swatches">${p.colors.slice(0,4).map(c=>`<span style="--swatch:${esc(c)}"></span>`).join('')}</div><div class="variant-copy">${p.variants.length?`${p.variants.length} VARIANTS`:'CURRENT COLORWAYS'}</div></div><div class="dossier-foot"><span>FROM ${money(p.price,p.currency)}</span><button class="dossier-open quick-trigger" data-index="${i}">OPEN DOSSIER →</button></div></article>`).join('');status.textContent=live?'LIVE FOURTHWALL CATALOG / CURRENT VAULT INVENTORY':'CURRENT VAULTLINE INVENTORY / FOURTHWALL CONNECTION STAGED';document.querySelectorAll('.quick-trigger').forEach(b=>b.onclick=()=>openQuick(+b.dataset.index))}
async function loadCatalog(){status.textContent='ACCESSING CURRENT VAULT INVENTORY…';try{const r=await fetch('/api/storefront/products');if(!r.ok)throw 0;const list=normalize(await r.json());if(!list.length)throw 0;render(list,true)}catch{render(fallbackProducts,false)}}
function openQuick(i){const p=products[i];if(!p)return;quickProduct=p;quickImage.src=p.image;quickImage.alt=p.name;quickName.textContent=p.name;quickDescription.textContent=p.copy;quickIndex.textContent=`VAULTLINE / ${String(i+1).padStart(3,'0')}`;quickSwatches.innerHTML=p.colors.map(c=>`<span style="--swatch:${esc(c)}"></span>`).join('');quickPrice.textContent=`FROM ${money(p.price,p.currency)}`;if(p.variants.length){quickVariants.innerHTML=`<select id="variant-select" style="max-width:230px;background:#090b0f;color:#f0f0ed;border:1px solid rgba(214,220,228,.18);padding:9px 10px;font:inherit">${p.variants.map(v=>`<option value="${esc(v.id)}" ${available(v)?'':'disabled'}>${esc(label(v))}${available(v)?'':' — SOLD OUT'}</option>`).join('')}</select>`;quickBuy.textContent='ADD TO CART';quickBuy.href='#';quickBuy.dataset.mode='cart'}else{quickVariants.textContent='VIEW ON FOURTHWALL';quickBuy.textContent='VIEW & BUY ON FOURTHWALL';quickBuy.href=`${STORE_URL}/products/${p.slug}`;quickBuy.dataset.mode='external'}quick.classList.add('open');scrim.classList.add('open');quick.setAttribute('aria-hidden','false');document.body.classList.add('locked')}
function closeQuick(){quick.classList.remove('open');quick.setAttribute('aria-hidden','true');if(!drawer.classList.contains('open'))scrim.classList.remove('open');document.body.classList.remove('locked')}
async function api(path,opt={}){const r=await fetch(path,{...opt,headers:{Accept:'application/json','Content-Type':'application/json',...(opt.headers||{})}}),body=await r.json().catch(()=>({}));if(!r.ok)throw new Error(body.error||`Request failed (${r.status})`);return body}
async function ensureCart(){const id=localStorage.getItem(CART_KEY);if(id){try{return await api(`/api/cart/${encodeURIComponent(id)}`)}catch{localStorage.removeItem(CART_KEY)}}const cart=await api('/api/cart',{method:'POST',body:'{"items":[]}'});localStorage.setItem(CART_KEY,cart.id);return cart}
function cartMath(cart){let count=0,total=0,currency='USD';for(const item of cart?.items||[]){const q=Number(item.quantity)||0,p=Number(item?.variant?.unitPrice?.value)||0;count+=q;total+=q*p;currency=item?.variant?.unitPrice?.currency||currency}return{count,total,currency}}
function showCart(cart){const {count,total,currency}=cartMath(cart);cartCount.textContent=count;cartTotal.textContent=money(total,currency);checkout.disabled=!cart?.id||!count;const items=cart?.items||[];if(!items.length){cartItems.innerHTML='<p class="cart-empty">Your Vaultline cart is empty.</p>';return}cartItems.innerHTML=items.map(item=>{const v=item.variant||{},q=Number(item.quantity)||1,img=v.images?.[0]?.transformedUrl||v.images?.[0]?.url||'';return`<article style="display:grid;grid-template-columns:72px 1fr;gap:14px;padding:14px 0;border-bottom:1px solid rgba(214,220,228,.18)">${img?`<img src="${esc(img)}" style="width:72px;height:86px;object-fit:contain;background:#0b0d11">`:''}<div><strong style="display:block;font-size:12px">${esc(v?.product?.name||v.name||'Vaultline piece')}</strong><span style="display:block;margin-top:5px;color:#a9b0ba;font-size:10px">${esc(label(v))}</span><div style="display:flex;gap:8px;align-items:center;margin-top:10px"><button data-a="dec" data-id="${esc(v.id)}" data-q="${q}">−</button><span>${q}</span><button data-a="inc" data-id="${esc(v.id)}" data-q="${q}">+</button><button data-a="remove" data-id="${esc(v.id)}" style="margin-left:auto;background:none;border:0;color:#a9b0ba;cursor:pointer">REMOVE</button></div></div></article>`}).join('');cartItems.querySelectorAll('[data-a]').forEach(b=>b.onclick=()=>changeItem(b))}
async function refreshCart(){const id=localStorage.getItem(CART_KEY);if(!id)return showCart({items:[]});try{showCart(await api(`/api/cart/${encodeURIComponent(id)}`))}catch{localStorage.removeItem(CART_KEY);showCart({items:[]})}}
async function changeItem(b){const id=localStorage.getItem(CART_KEY),variantId=b.dataset.id,q=+b.dataset.q||1,a=b.dataset.a;if(!id)return;const remove=a==='remove'||(a==='dec'&&q<=1),path=`/api/cart/${encodeURIComponent(id)}/${remove?'remove':'change'}`,items=remove?[{variantId}]:[{variantId,quantity:a==='inc'?q+1:q-1}];showCart(await api(path,{method:'POST',body:JSON.stringify({items})}))}
async function addSelected(e){if(quickBuy.dataset.mode!=='cart')return;e.preventDefault();const variantId=$('#variant-select')?.value;if(!variantId)return;quickBuy.textContent='ADDING…';try{const cart=await ensureCart(),next=await api(`/api/cart/${encodeURIComponent(cart.id)}/add`,{method:'POST',body:JSON.stringify({items:[{variantId,quantity:1}]})});showCart(next);closeQuick();openCart()}catch{quickBuy.textContent='VIEW & BUY ON FOURTHWALL';quickBuy.href=`${STORE_URL}/products/${quickProduct.slug}`;quickBuy.dataset.mode='external'}finally{if(quickBuy.dataset.mode==='cart')quickBuy.textContent='ADD TO CART'}}
function openCart(){drawer.classList.add('open');scrim.classList.add('open');drawer.setAttribute('aria-hidden','false');document.body.classList.add('locked');refreshCart()}
function closeCart(){drawer.classList.remove('open');drawer.setAttribute('aria-hidden','true');if(!quick.classList.contains('open'))scrim.classList.remove('open');document.body.classList.remove('locked')}
toggle.onclick=()=>{const o=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',String(o))};cartButton.onclick=openCart;cartClose.onclick=closeCart;quickClose.onclick=closeQuick;quickBuy.onclick=addSelected;scrim.onclick=()=>{closeQuick();closeCart()};$('#refresh-products').onclick=loadCatalog;checkout.onclick=()=>{const id=localStorage.getItem(CART_KEY);if(id)location.assign(`${STORE_URL}/checkout/?cartId=${encodeURIComponent(id)}&cartCurrency=USD`)};document.querySelectorAll('[data-feature-slug]').forEach(el=>el.onclick=()=>{const i=products.findIndex(p=>p.slug===el.dataset.featureSlug);openQuick(i<0?3:i)});document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeQuick();closeCart()}});loadCatalog();refreshCart();
