const STORE_URL='https://vaultlineofficial.us';
const fallbackProducts=[
{name:'In Ruin We Trust Slides',slug:'in-ruin-we-trust-slides',price:36,image:'https://cdn.fourthwall.com/customizations/sh_0e0db572-47ce-453b-a747-142819f87a74/699ce60f-5fb4-4dcb-855a-74d3f865b6ee.png',accent:'steel',copy:'Built for the aftermath. Dark, understated, and unmistakably Vaultline.',colors:['#0e0c0f','#f1f1ef'],variants:'BLACK / WHITE'},
{name:'White Sigil Rib Tank',slug:'white-sigil-rib-tank',price:25,image:'https://cdn.fourthwall.com/customizations/sh_0e0db572-47ce-453b-a747-142819f87a74/26b306d0-ab15-4974-9a9e-8729093d77d6.webp',accent:'pearl',copy:'Minimal from the front. Quietly marked from behind.',colors:['#0c0c0c','#243048','#aeb0b2'],variants:'BLACK / NAVY / HEATHER'},
{name:'Crimson Thorn Baby Tee',slug:'crimson-thorn-baby-tee-vaultline-by-gizzy-graves',price:37,image:'https://cdn.fourthwall.com/customizations/sh_0e0db572-47ce-453b-a747-142819f87a74/54978fa7-1209-4d1c-9283-ff4f848068a1.webp',accent:'crimson',copy:'The front stays restrained. The back carries the damage.',colors:['#19171b','#3c2926','#e6e7e9'],variants:'BLACK / BROWN / WHITE'},
{name:'Northern Fracture Hoodie',slug:'vaultline-northern-fracture-hoodie',price:62,image:'https://cdn.fourthwall.com/customizations/sh_0e0db572-47ce-453b-a747-142819f87a74/69a3a0b2-52a8-4383-954c-f7c5383ceef2.webp',accent:'vault',copy:'Heavy structure. Northern Star. Controlled fracture.',colors:['#0f0f0f','#30478a','#aeb0b2'],variants:'BLACK / COBALT / HEATHER'},
{name:'Northern Thorn Cami',slug:'northern-thorn-cami-vaultline',price:25,image:'https://cdn.fourthwall.com/customizations/sh_0e0db572-47ce-453b-a747-142819f87a74/6099ed73-bac7-49c4-ac3d-514c6c67aca0.png',accent:'crimson',copy:'A softer silhouette without losing the edge.',colors:['#0c0c0c'],variants:'BLACK'},
{name:'IXXI Vaultline Tee',slug:'ixxi-vaultline-tee',price:38,image:'https://cdn.fourthwall.com/offer/sh_0e0db572-47ce-453b-a747-142819f87a74/00db2ce5-1ceb-4aee-8ad5-673047373ab1.png',accent:'pearl',copy:'IXXI at the front. Vaultline fracture language at the back.',colors:['#424242'],variants:'FADED BLACK'},
{name:'Half Butterfly Fracture Baby Tee',slug:'half-butterfly-fracture-baby-tee',price:38,image:'https://cdn.fourthwall.com/customizations/sh_0e0db572-47ce-453b-a747-142819f87a74/bbf26803-a430-4b71-af64-5167312caf82.webp',accent:'crimson',copy:'Transformation without erasure. Split through the fracture.',colors:['#19171b'],variants:'BLACK'},
{name:'Vaultline Gift Card',slug:'vaultline-gift-card',price:25,image:'https://cdn.fourthwall.com/offer/sh_0e0db572-47ce-453b-a747-142819f87a74/c2f2de89-d029-47a8-8446-ab2cabd39270.png',accent:'steel',copy:'Give them access to the Vault. Let them choose the piece.',colors:['#11151c'],variants:'$25 / $50 / $100 / $150 / $200'}
];
let currentProducts=fallbackProducts;
const grid=document.querySelector('#product-grid'),status=document.querySelector('#catalog-status'),nav=document.querySelector('#site-nav'),toggle=document.querySelector('.nav-toggle'),drawer=document.querySelector('#cart-drawer'),scrim=document.querySelector('#scrim'),cartButton=document.querySelector('#cart-button'),cartClose=document.querySelector('#cart-close'),checkoutButton=document.querySelector('#checkout-button'),cartItems=document.querySelector('#cart-items');
const quick=document.querySelector('#quick-view'),quickClose=document.querySelector('#quick-close'),quickImage=document.querySelector('#quick-image'),quickName=document.querySelector('#quick-name'),quickDescription=document.querySelector('#quick-description'),quickIndex=document.querySelector('#quick-index'),quickSwatches=document.querySelector('#quick-swatches'),quickVariants=document.querySelector('#quick-variants'),quickPrice=document.querySelector('#quick-price'),quickBuy=document.querySelector('#quick-buy');
function money(v,c='USD'){return new Intl.NumberFormat('en-US',{style:'currency',currency:c}).format(Number(v)||0)}
function normalizeProducts(payload){const list=Array.isArray(payload)?payload:(payload.products||payload.data||payload.items||[]);return list.map((p,i)=>({name:p.name||p.title||'Vaultline piece',slug:p.slug||p.handle||p.id,price:p.price?.amount||p.price||p.variants?.[0]?.price?.amount||p.variants?.[0]?.price||0,currency:p.price?.currency||p.currency||p.variants?.[0]?.currency||'USD',image:p.primaryImageUrl||p.image?.url||p.images?.[0]?.url||p.images?.[0]||'',url:p.url||null,copy:'A piece pulled from the current Vaultline catalog.',accent:i%3===0?'crimson':i%3===1?'pearl':'steel',colors:['#151515'],variants:'CURRENT COLORWAYS'})).filter(p=>p.name)}
function renderProducts(products,live=false){currentProducts=products;grid.innerHTML=products.map((p,i)=>`<article class="product-card accent-${p.accent||'steel'}"><div class="dossier-head"><div class="dossier-title"><span class="dossier-number">${String(i+1).padStart(2,'0')}.</span><h3>${p.name}</h3></div><p>${p.copy||''}</p></div><button class="product-visual quick-trigger" data-index="${i}" aria-label="Inspect ${p.name}"><img src="${p.image}" alt="${p.name}" loading="lazy"><span class="view-stamp">INSPECT PIECE</span></button><div class="colorway-label">COLORWAYS</div><div class="colorway-row"><div class="swatches">${(p.colors||['#151515']).map(c=>`<span style="--swatch:${c}"></span>`).join('')}</div><div class="variant-copy">${p.variants||'CURRENT VARIANTS'}</div></div><div class="dossier-foot"><span>FROM ${money(p.price,p.currency||'USD')}</span><button class="dossier-open quick-trigger" data-index="${i}">OPEN DOSSIER →</button></div></article>`).join('');status.textContent=live?'LIVE FOURTHWALL CATALOG / CURRENT VAULT INVENTORY':'CURRENT VAULTLINE INVENTORY / FOURTHWALL CONNECTION STAGED';document.querySelectorAll('.quick-trigger').forEach(el=>el.addEventListener('click',()=>openQuick(Number(el.dataset.index))))}
async function loadCatalog(){status.textContent='ACCESSING CURRENT VAULT INVENTORY…';try{const res=await fetch('/api/storefront/products',{headers:{Accept:'application/json'}});if(!res.ok)throw new Error();const products=normalizeProducts(await res.json());if(!products.length)throw new Error();renderProducts(products,true)}catch(e){renderProducts(fallbackProducts,false)}}
function openQuick(index){const p=currentProducts[index];if(!p)return;quickImage.src=p.image||'';quickImage.alt=p.name;quickName.textContent=p.name;quickDescription.textContent=p.copy||'';quickIndex.textContent=`VAULTLINE / ${String(index+1).padStart(3,'0')}`;quickSwatches.innerHTML=(p.colors||['#151515']).map(c=>`<span style="--swatch:${c}"></span>`).join('');quickVariants.textContent=p.variants||'CURRENT VARIANTS';quickPrice.textContent=`FROM ${money(p.price,p.currency||'USD')}`;quickBuy.href=p.url||`${STORE_URL}/products/${p.slug}`;quick.classList.add('open');scrim.classList.add('open');quick.setAttribute('aria-hidden','false');document.body.classList.add('locked')}
function closeQuick(){quick.classList.remove('open');quick.setAttribute('aria-hidden','true');if(!drawer.classList.contains('open'))scrim.classList.remove('open');document.body.classList.remove('locked')}
function openCart(){drawer.classList.add('open');scrim.classList.add('open');drawer.setAttribute('aria-hidden','false');cartItems.innerHTML='<p class="cart-empty">Cart handoff is staged for the Fourthwall Storefront connection.</p>'}function closeCart(){drawer.classList.remove('open');drawer.setAttribute('aria-hidden','true');if(!quick.classList.contains('open'))scrim.classList.remove('open')}
toggle.addEventListener('click',()=>{const o=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',String(o))});cartButton.addEventListener('click',openCart);cartClose.addEventListener('click',closeCart);quickClose.addEventListener('click',closeQuick);scrim.addEventListener('click',()=>{closeQuick();closeCart()});document.querySelector('#refresh-products').addEventListener('click',loadCatalog);checkoutButton.addEventListener('click',()=>window.location.assign(STORE_URL));document.querySelectorAll('[data-feature-slug]').forEach(el=>el.addEventListener('click',()=>{const i=currentProducts.findIndex(p=>p.slug===el.dataset.featureSlug);openQuick(i<0?3:i)}));document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeQuick();closeCart()}});loadCatalog();